version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "81:81"
    links:
      - app
    networks:
      - front-tier
      - back-tier
  app:
    build: .
    command: python server.py 8081
    expose:
      - "8081"
    volumes:
    - .:/app
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
