version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "81:81"
    links:
      - app1
      - app2
  app1:
    build: .
    command: python server.py 8081
    expose:
      - "8081"
    volumes:
    - .:/app
  app2:
    build: .
    command: python server.py 8082
    expose:
      - "8082"
    volumes:
    - .:/app
